# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: backend component

## on:
  ## workflow_dispatch:
    ## inputs:
      ## environment:
        ## description: 'Choose environment'
        ## required: true
        ## default: 'production'
        ## type: choice
        ## options:
        ## - PROD
        ## - NFT
        ## - UAT

on:
  pull_request:
    branches:
      - 'release'
      - 'main'
env:
  ENV_DEST: ${{ github.base_ref }}

jobs:
## Mostramos todas las variables del workflow
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
## Validamos  que los componenetes que se han establecido en el Json de release , estan 
  validation-release:
    needs: one
    if: github.event_name == 'pull_request' && github.base_ref == 'release'
    # if: github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'path/to/file')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref }}"
        uses: ./.github/validation/
# mergeamos la pull request a la rama Release  para dejarla preparada para propagar la
  automerge:
    needs: 'validation-release'
    if: github.event_name == 'pull_request' && github.base_ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: execute merge
        uses: "gsoc2/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_PULLREQ }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "rebase"
          PULL_REQUEST: "${{ github.event.pull_request.number }}"
          LOG: "DEBUG"
  